# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rental-price-predictor-service
spec:
  selector:
    app: rental-price-predictor
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
